filters:
  - ../container-writer.lua
    
format:
  pdf:
    include-in-header: styles/demo-preamble.tex
  html:
    css: styles/demo.css
  context:
    include-in-header: styles/demo.ctx
  typst:
    include-in-header: styles/demo.typ
